version: '3.3'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql-docker/data:/var/opt/mssql/data
      - /var/opt/mssql-docker/log:/var/opt/mssql/log
    
    environment:
      MSSQL_SA_PASSWORD: "zLq60A!eb342o0N2"
      ACCEPT_EULA: "Y"